# Generated by Django 5.2.1 on 2025-05-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
